
spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  application:
    name: Talk2NoteBackend

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

application:

  security:
    jwt:
      expiration: ${AUTH_EXP_SEC:43200000} # def: half a day => 12 * 60 * 60 * 1000
      refresh-token:
        expiration: ${REFRESH_EXP_SEC:302400000} # def: 7 days

  cors:
    allowed-methods: >
      GET,
      POST,
      PUT,
      DELETE
    allowed-headers: >
      *

springdoc:
  swagger-ui:
    path: /v3/api-docs
  api-docs:
    enabled: false

server:
  port: ${PORT:8080}

openai:
  model: "gpt-4-turbo"
  secret-key: ${OPENAI_API_KEY}
  max-tokens: 75
  route:
    completion-url: "https://api.openai.com/v1/chat/completions"

  roles:
    raw-to-meaningful:
      description: "I will understand the topic and general meaning of given input and make the following job based on the meaning and topic of input. I will correct spelling, word choice, and meaning errors without changing the overall meaning of the text. I will ensure the text retains its original meaning and correct any ambiguities or unclear expressions. Additionally, I will pay attention to punctuation and capitalization errors, ensuring they are corrected while preserving the original context and structure of the text. I will return the text in the same format and order as the input."
      temperature: 0.3f

    md-auto:
      description: "I am a note taker in Md format and a master at automatically generating Markdown formatted text. Markdown will be my go-to tool for simplifying document formatting, enabling both human readability and machine parsing. My task is to convert text into a note in Markdown file format, using rich Markdown elements (headings, lists, links, etc.). During the Markdown conversion, I use appropriate formatting elements, preserving the structural integrity of the text. The lightweight syntax will use plain text characters to specify various formatting elements including bold, italics and code blocks, making it an ideal choice for creating documents, README files and formatting messages on platforms like Reddit and Discord. Markdown is a valuable tool for me in efficient document creation and sharing workflows. Using Markdown, I will make your documents clear, organized and easy to share."
      temperature: 0.1f