
spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  application:
    name: Talk2NoteBackend

  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

application:

  security:
    jwt:
      expiration: ${AUTH_EXP_SEC:43200000} # def: half a day => 12 * 60 * 60 * 1000
      refresh-token:
        expiration: ${REFRESH_EXP_SEC:302400000} # def: 7 days

  cors:
    allowed-methods: >
      GET,
      POST,
      PUT,
      DELETE
    allowed-headers: >
      *

springdoc:
  swagger-ui:
    path: /v3/api-docs
  api-docs:
    enabled: false

server:
  port: ${PORT:8080}

openai:
  model: "gpt-3.5-turbo"
  secret-key: ${OPENAI_API_KEY}
  max-tokens: 75
  route:
    completion-url: "https://api.openai.com/v1/completions"

  role:
    description:
      raw-to-meaningful: "As a 'raw-to-meaningful' role, this actor specializes in converting unstructured or raw text into coherent and meaningful sentences. It employs advanced natural language processing techniques to analyze and interpret the input text, extracting key information and structuring it into clear and understandable sentences. This role is ideal for tasks such as summarization, paraphrasing, or text generation where the goal is to transform raw data into actionable insights or readable content."
      md-auto: "The 'md-auto' role excels in automatically generating Markdown-formatted text. It intelligently formats input text into Markdown syntax, handling headings, lists, links, and other Markdown elements seamlessly. This role is particularly useful for automating the creation of documentation, blog posts, or any content that requires Markdown formatting. By automating the Markdown conversion process, it saves time and effort while ensuring consistency and accuracy in the output."