
spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  application:
    name: Talk2NoteBackend

  jpa:
    hibernate:
      ddl-auto: ${DB_DLL:update}
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+3
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  jackson:
    property-naming-strategy: SNAKE_CASE

application:

  security:
    jwt:
      secret-key: ${AUTH_SECRET:50655367566B5970337336763979244226452948404D635166546A576D5A7134743777217A25432A462D4A614E645267556B58703272357538782F413F4428472B4B6250655368566D5971337436763979244226452948404D635166546A576E5A7234753778217A25432A462D4A614E645267556B58703273357638792F423F}
      expiration: ${AUTH_EXP_SEC:43200000} # def: half a day => 12 * 60 * 60 * 1000
      refresh-token:
        expiration: ${REFRESH_EXP_SEC:302400000} # def: 7 days

  cors:
    allowed-origins: >
      http://localhost:3000,
      http://localhost:5173
    allowed-methods: >
      GET,
      POST,
      PUT,
      DELETE
    allowed-headers: >
      *